version: "3"

services:
    dj:
        container_name: dj
        build: django
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - ./django:/code
        ports:
            - "80:80"
        depends_on:
          - db

    db:
        image: mysql:8.0.20
        environment:
          MYSQL_ROOT_PASSWORD: vdsforeverr
          MYSQL_DATABASE: restaurantratingsystem
        ports:
            - "3308:3306"