# Generated by Django 3.0.6 on 2020-06-28 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('level_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('points_level', models.PositiveIntegerField()),
                ('allocated_comfirmation_points', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_level_reated_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_level_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_status', models.PositiveSmallIntegerField()),
                ('email_code', models.CharField(max_length=255)),
                ('email_verified', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
                ('gender', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('updated_on', models.DateTimeField()),
                ('level_number', models.ForeignKey(db_column='level_number', on_delete=django.db.models.deletion.PROTECT, to='restaurantratingapi.UserLevel')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='restaurantratingapi.UserRole')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_user',
                'managed': True,
            },
        ),
    ]
