# Generated by Django 3.0.6 on 2020-12-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantratingapi', '0003_auto_20200801_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', default=3, on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_rating_restaurant', to='restaurantratingapi.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
